expected_batch_size: 32
visible_devices: "0"
n_gpu: 1
check_already_trained: True
check_git_status: True
dev: False
training_arguments:
  per_device_train_batch_size: 32
  gradient_accumulation_steps: 1
  learning_rate: 2.0e-5
  num_train_epochs: 10
  evaluation_strategy: 'epoch'
  save_strategy: 'epoch'
  warmup_ratio: .01
  logging_steps: 25
  save_total_limit: 10